[package]
name = "modloader_api"
version = "0.1.0"
edition = "2021"

crate-type = ["dylib"]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]